analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3431801,"name"\:"DemoBlaze","teamId"\:3403129,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3469599,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3403129,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.hub.switchHub.enable=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
