<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_carousel-control-next-icon</name>
   <tag></tag>
   <elementGuidId>074fc84e-35ef-4ae1-a2a3-2509f27da09e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.carousel-control-next-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' carousel-control-next-icon ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#carouselExampleIndicators >> internal:role=button[name=&quot;Next&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5a94f1db-309a-493b-aae0-57b94cda7b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-control-next-icon</value>
      <webElementGuid>1ae26bc1-6776-4ca3-9b7c-35eafc35e9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d9d3cf97-a68d-4e9e-99f5-d9c598b25ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-797df6f90d3604fdc14dc3dc7e8874e3</value>
      <webElementGuid>64b83ff9-eb9f-41f8-b3b9-bfe18ff60d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' carousel-control-next-icon ')]</value>
      <webElementGuid>aca60078-46e3-492c-9ba4-ada38b0c710c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' carousel-control-next-icon ')]</value>
      <webElementGuid>94c88475-e71b-421a-88ac-0b2cb5b53e93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
