<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_example-video_html5_api</name>
   <tag></tag>
   <elementGuidId>1670521d-bba4-4917-9179-eb22991f9255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.vjs-tech</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' vjs-tech ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#example-video_html5_api</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>f295f2a2-ee97-4b4f-950f-5760cbc8cd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>poster</name>
      <type>Main</type>
      <value>imgs/front.jpg</value>
      <webElementGuid>ffbfd053-7807-4210-a75d-2fbba7fa92bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>example-video_html5_api</value>
      <webElementGuid>c54fcf5e-7c1e-4d9b-a0af-21b4b6daa49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-tech</value>
      <webElementGuid>0d955ecc-a4d7-4036-9e55-b2c3bad1817d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ffa7f78b-2c1f-49ed-b798-232ef397ac82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>application</value>
      <webElementGuid>d5d67174-4fbe-4774-9c4d-63511564a328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hls.demoblaze.com/index.m3u8</value>
      <webElementGuid>884c038c-d758-462b-94b5-cfcdf4e83c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1d381e012af7bf70c5555000706af5ec</value>
      <webElementGuid>21dde3ef-b340-4bb1-9ac1-8d32e4e08d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' vjs-tech ')]</value>
      <webElementGuid>063c0b1a-ce3a-4a8a-9f0b-2a307359c83a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' vjs-tech ')]</value>
      <webElementGuid>55042b39-143b-4989-b9ae-954e08afcfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'example-video_html5_api' and @src = 'https://hls.demoblaze.com/index.m3u8']</value>
      <webElementGuid>81857740-0aeb-41cb-a536-5f9a336534a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
